#!/usr/bin/env python3
"""Regenerate registry/mods/map-spawn-rate/settings/maps.json from rAthena's spawn scripts.

A development tool, run by whoever updates the mod -- never by the app. The
mod ships the generated maps.json, committed; nothing a player installs runs
Python. It lives outside the mod folder because the registry index does not
carry .py files.

    python3 registry/tools/map-spawn-rate/generate.py            # rewrite it
    python3 registry/tools/map-spawn-rate/generate.py --check    # fail if stale

maps.json is only what the mod's settings page lists: every map with a stock
monster spawn, and what spawns there, per era. The server does the scaling
itself, from its own scripts, so a stale list can at worst leave a map out of
the picker -- never change what a rate does.

By default it reads vendor/rathena, which should be the commit
config/VENDOR_PINS names (`scripts/vendor-fetch.sh rathena vendor/rathena`).
`--source` reads another copy instead.

The spawns loaded are the ones rAthena loads: the `npc:` lines of
npc/scripts_monsters.conf and npc/<era>/scripts_monsters.conf, in that order,
skipping commented-out ones. Standard library only.
"""

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
OUTPUT = os.path.join(REPO, "registry", "mods", "map-spawn-rate", "settings", "maps.json")
ERAS = {"renewal": "re", "pre-renewal": "pre-re"}

# <map>,<x>,<y>{,<xs>,<ys>}<TAB>monster|boss_monster<TAB><name>{,<level>}<TAB><id>,<amount>,...
SPAWN = re.compile(r"^([A-Za-z0-9_@.-]+),[^\t]*\t(monster|boss_monster)\t([^\t,]+)[^\t]*\t\s*(\d+)\s*,\s*(\d+)")
NPC_LINE = re.compile(r"^npc:\s*(\S+)")


def script_list(source, conf):
    path = os.path.join(source, conf)
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8", errors="replace") as f:
        return [m.group(1) for line in f if (m := NPC_LINE.match(line.strip()))]


def strip_block_comments(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def era_maps(source, era_dir):
    maps = {}
    files = script_list(source, "npc/scripts_monsters.conf") + script_list(source, f"npc/{era_dir}/scripts_monsters.conf")
    if not files:
        sys.exit(f"no spawn scripts listed under {source}/npc -- is --source an rAthena checkout?")
    for rel in files:
        path = os.path.join(source, rel)
        if not os.path.exists(path):
            sys.exit(f"{rel} is listed in scripts_monsters.conf but missing")
        with open(path, encoding="utf-8", errors="replace") as f:
            text = strip_block_comments(f.read())
        for line in text.splitlines():
            if line.lstrip().startswith("//"):
                continue
            m = SPAWN.match(line)
            if not m:
                continue
            mapname, kind, name, mob_id, amount = m.group(1), m.group(2), m.group(3).strip(), int(m.group(4)), int(m.group(5))
            if amount <= 0:
                continue
            lines = maps.setdefault(mapname, {})
            key = (name, mob_id)
            # A monster can have several lines on one map; keep them apart by
            # whether they scale (a single-monster line does not).
            entry = lines.setdefault(key, [name, mob_id, 0, 0])
            if amount > 1:
                entry[2] += amount
            else:
                entry[3] += 1
    out = {}
    for mapname in sorted(maps):
        mobs = sorted(maps[mapname].values(), key=lambda e: (-(e[2] + e[3]), e[0]))
        out[mapname] = mobs
    return out


def pinned_commit(source):
    try:
        return subprocess.run(["git", "-C", source, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def render(source):
    data = {
        "_comment": "Generated by registry/tools/map-spawn-rate/generate.py; do not edit. "
                    "Each monster is [name, id, monsters on lines that scale, single-monster lines that do not].",
        "rathena": pinned_commit(source),
        "eras": {era: era_maps(source, d) for era, d in ERAS.items()},
    }
    return json.dumps(data, separators=(",", ":"), ensure_ascii=False) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--source", default=os.path.join(REPO, "vendor", "rathena"))
    parser.add_argument("--check", action="store_true", help="fail if maps.json is stale")
    args = parser.parse_args()
    text = render(args.source)
    if args.check:
        current = open(OUTPUT, encoding="utf-8").read() if os.path.exists(OUTPUT) else ""
        if current != text:
            sys.exit(f"{os.path.relpath(OUTPUT, REPO)} is stale; run {os.path.relpath(__file__, REPO)}")
        return
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    eras = json.loads(text)["eras"]
    print(", ".join(f"{era}: {len(m)} maps" for era, m in eras.items()))


if __name__ == "__main__":
    main()
