#!/usr/bin/env python3
"""Write tools/control-panel/job-names.js: rAthena's English name for each job.

The Control panel (Settings -> Tools, #230) names a character's job the way the
server does: `job_name()` in src/map/pc.cpp maps a job id to a line of
conf/msg_conf/map_msg.conf. The panel runs without the server's sources, so
the table is generated here from the pinned rAthena and committed. Run it
again after the rAthena pin moves:

    scripts/vendor-fetch.sh rathena vendor/rathena
    python3 scripts/control-panel-job-names.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RATHENA = ROOT / "vendor" / "rathena"
OUT = ROOT / "tools" / "control-panel" / "job-names.js"


def jobs():
    """enum e_job (src/common/mmo.hpp): name -> id."""
    text = (RATHENA / "src/common/mmo.hpp").read_text()
    body = re.search(r"enum e_job\s*\{(.*?)\};", text, re.S).group(1)
    out, n = {}, -1
    for line in body.splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line:
            continue
        m = re.fullmatch(r"(JOB_\w+)(?:\s*=\s*(\w+))?", line)
        if not m:
            continue
        if m.group(2):
            n = int(m.group(2), 0) if m.group(2)[0].isdigit() else out[m.group(2)]
        else:
            n += 1
        out[m.group(1)] = n
    return out


def messages():
    out = {}
    for line in (RATHENA / "conf/msg_conf/map_msg.conf").read_text(errors="replace").splitlines():
        m = re.match(r"^(\d+):\s*(.*)$", line)
        if m:
            out[int(m.group(1))] = m.group(2).strip()
    return out


def names():
    ids, msg = jobs(), messages()
    text = (RATHENA / "src/map/pc.cpp").read_text()
    body = re.search(r"const char\* job_name\(int32 class_\)\s*\{(.*?)\n\}", text, re.S).group(1)
    out, cases = {}, []
    for line in body.splitlines():
        for case in re.findall(r"case\s+(JOB_\w+)\s*:", line):
            cases.append(ids[case])
        ret = re.search(r"return\s+msg_txt\(\s*nullptr\s*,\s*(\d+)\s*(?:-\s*(JOB_\w+)\s*\+\s*class_)?\s*\)", line)
        if ret:
            for job in cases:
                index = int(ret.group(1)) - (ids[ret.group(2)] if ret.group(2) else 0) + (job if ret.group(2) else 0)
                out.setdefault(job, msg[index])
            cases = []
        elif "return" in line or "default:" in line:
            cases = []
    return dict(sorted(out.items()))


def main():
    if not RATHENA.is_dir():
        sys.exit("vendor/rathena is missing: run scripts/vendor-fetch.sh rathena vendor/rathena")
    table = names()
    OUT.write_text(
        "// Generated by scripts/control-panel-job-names.py from rAthena's job_name()\n"
        "// (src/map/pc.cpp) and conf/msg_conf/map_msg.conf. Do not edit by hand.\n"
        f"window.JOB_NAMES = {json.dumps(table, indent=1, ensure_ascii=False)};\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(table)} jobs")


if __name__ == "__main__":
    main()
